[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--strict-markers -ra -q"
testpaths = [
    "tests"
]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
# Omit files or patterns from the coverage report
omit = [
    "run.py",
]